stages:
  - build
  - deploy


build:
  image: node:10
  stage: build
  before_script:
    # - npm config set registry=https://registry.npm.taobao.org
    # - npm install -g yarn
    - yarn config set registry https://registry.npm.taobao.org
    - yarn add -D vuepress
  script:
    - echo "==== docs build ===="
    - yarn docs:build
    - tar zcvf target/dist-$CI_COMMIT_REF_NAME.tar.gz docs/.vuepress/dist
  cache:
    paths:
      - node_modules/ # Node modules and dependencies
  tags:
    - rdep-docs
  artifacts:
    name: "artifacts_$CI_COMMIT_REF_NAME_$CI_COMMIT_SHORT_SHA"
    expire_in: 3 day
    paths:
      - docs/.vuepress/dist

    
# the 'pages' job will deploy and build your site to the 'public' path
deploy:
  image: alpine
  stage: deploy
  script: 
    - echo "==== docs deploy ===="
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host 10.2.28.253\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete docs/.vuepress/dist/ root@10.2.28.253:/root/cloudwise/test/
  only:
    - master
  tags: 
    - rdep-docs
